# Generated by Django 4.0.1 on 2022-01-17 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='client_records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=200, null=True)),
                ('client_name', models.CharField(max_length=200, null=True)),
                ('client_location', models.CharField(max_length=200, null=True)),
                ('shoot_date', models.DateField(max_length=200, null=True)),
                ('coureir_date', models.DateField(max_length=200, null=True)),
                ('return_date', models.DateField(max_length=200, null=True)),
                ('booked_dress', models.CharField(max_length=200, null=True)),
                ('payment_type', models.CharField(max_length=200, null=True)),
                ('cost_details', models.CharField(max_length=200, null=True)),
                ('received_date', models.DateField(max_length=200, null=True)),
                ('status', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='dress_records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dress_id', models.CharField(max_length=200, null=True)),
                ('dress_name', models.CharField(max_length=200, null=True)),
                ('cost', models.IntegerField(max_length=200, null=True)),
                ('category', models.CharField(max_length=200, null=True)),
                ('dress_image', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='signin_credentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, null=True)),
                ('password', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
