# Generated by Django 4.0.1 on 2022-01-11 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LogIn', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='signin_credentials',
            new_name='login_credentials',
        ),
    ]
